services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Harmony\Bundle\CoreBundle\Controller\HomeController: ~

  Harmony\Bundle\CoreBundle\EventSubscriber\RouterListener: ~

  Harmony\Bundle\CoreBundle\Form\Type\UserRoleType:
    arguments:
      $roleHierarchy: '%security.role_hierarchy.roles%'