services:
  Harmony\Bundle\CoreBundle\EventSubscriber\RouterListener:
    arguments: ['@router', '@request_stack', '@router.request_context', '@logger', '%kernel.project_dir%', '%kernel.debug%']
    tags:
      -  { name: kernel.event_subscriber }