services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $entityManager: '@doctrine.orm.default_entity_manager'
      $settingsEntityClass: 'Harmony\Bundle\CoreBundle\Entity\Setting'
      $tagEntityClass: 'Harmony\Bundle\CoreBundle\Entity\SettingTag'
      $providers: { config: '@settings_manager.provider.config' }

  Harmony\Bundle\CoreBundle\EventSubscriber\RouterListener: ~

  Helis\SettingsManagerBundle\Provider\DoctrineOrmSettingsProvider: ~

  Harmony\Bundle\CoreBundle\Manager\SettingsManager: ~
