Helis\SettingsManagerBundle\Model\SettingModel:
  constraints:
    - Helis\SettingsManagerBundle\Validator\Constraints\SettingType: { groups: [CoreSettingValidation] }
  properties:
    name:
      - NotBlank: { message: 'Setting name should not be blank', groups: [CoreSettingValidation] }
    domain:
      - NotNull: { message: 'Setting should have a domain', groups: [CoreSettingValidation] }
    type:
      - NotNull: { message: 'Setting should have a type', groups: [CoreSettingValidation] }